# Generated by Django 4.0.8 on 2022-10-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dist', models.CharField(max_length=25)),
                ('calle', models.CharField(max_length=25)),
                ('numero_casa', models.PositiveIntegerField()),
                ('colonia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='distributor',
            fields=[
                ('id_dist', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dist', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='phone_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dist', models.CharField(max_length=25)),
                ('numero_telefono', models.PositiveBigIntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
